jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug ECR registry output
        run: echo "Registry is ${{ steps.login-ecr.outputs.registry }}"  

  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      ECR_REGISTRY: ${{ needs.job1.outputs.ecr_registry }}
    steps:
      - name: Dump all job1 outputs
        run: |
          echo "Job1 outputs:"
          echo "${{ toJson(needs.job1.outputs) }}"


      - name: Use the registry
        run: echo "Pushing to $ECR_REGISTRY"

      - name: Print ECR registry from login job
        run: echo "ECR Registry is ${{ needs.job1.outputs.ecr_registry }}"
