name: Passing Secrets Example

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Ensures job2 waits for job1 to complete
    env:
      ECR_REGISTRY: ${{ needs.job1.outputs.ecr_registry }}
    steps:
      - name: Use the registry
        run: echo "Pushing to $ECR_REGISTRY"

      - name: Print ECR registry from login job
        run: echo "ECR Registry is ${{ needs.job1.outputs.ecr_registry }}"